Create Initial Data Schema
GTBitsOfGood/boggers pull request #17
Opened 2022-09-30 21:05 UTC by bat-kryptonyte

## PR Create Initial Data Schema

Issue Number(s): #11

What does this PR change and why?
Added new schema fields

### Related PRs 
None

### How to Test

yarn dev

MongoDB
A running instance of MongoDB is required this project.

Locally (Docker - RECOMMENDED)
[Download Docker Desktop](https://www.docker.com/products/docker-desktop)
Run docker run --name mongodb -d -p 27017:27017 mongo in your terminal
Open Docker Desktop and confirm that your MongoDB image is running. It should exist on port 27017, and can be accessed.
Locally (Non-Docker)
[Download MongoDB Community Server](https://www.mongodb.com/download-center/community)
Go through the installation instructions.
Leave the port at default 27017

2022-10-01 03:52 UTC, kphan32 requested changes

2022-10-01 03:52 UTC, kphan32 commented on server/mongodb/models/InitSchema.js
> +    },
The semester declaration should be defined at the top and re-used

2022-10-01 03:52 UTC, kphan32 commented on server/mongodb/models/InitSchema.js
> +}
🤔 prettier?

2022-10-01 03:55 UTC, kphan32 commented
oh-- also don't forget the pull in the fields in the `User` schema defined by `next-auth`.

2022-10-01 06:36 UTC, kphan32 commented
also also.. just updated the original ticket to remove the projects schema. realized that it probably isn't needed

2022-10-11 23:20 UTC, therealsharath commented
@bat-kryptonyte could you please re-request a review and add me as a reviewer? 🤔

2022-10-20 20:52 UTC, closed without merging